import Head from 'next/head'
import { useState, useEffect } from 'react'
import { parseCookies } from '../lib/parseCookies'
import usePersistLogin from '../hooks/usePersistLogin'
import styles from '../styles/Index.module.css'

export default function Home({ initialPersistValue }) {
  const persistLogin = usePersistLogin(initialPersistValue)

  return (
    <div className={styles.container}>
      {persistLogin(
        <>
          <Head>
            <title>Planner App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <div className={styles.block}>
            <h1>Welcome!</h1>
          </div>
          <div></div>
        </>
      )}
    </div>
  )
}
Home.getInitialProps = ({ req }) => {
  const cookies = parseCookies(req)
  return {
    initialPersistValue: cookies.persist,
  }
}
