import Head from 'next/head'
import { useState, useEffect } from 'react'
import { parseCookies } from '../lib/parseCookies'
import usePersistLogin from '../hooks/usePersistLogin'
import styles from '../styles/Index.module.css'
import Link from 'next/link'

export default function Home({ initialPersistValue }) {
  const persistLogin = usePersistLogin(initialPersistValue)
  const [time, setTime] = useState()

  const date = new Date()

  useEffect(() => {
    const timer = setInterval(
      () =>
        setTime(
          new Intl.DateTimeFormat('en-US', {
            dateStyle: 'full',
            timeStyle: 'long',
          }).format(date)
        ),
      1000
    )
    return () => {
      clearInterval(timer)
    }
  }, [time])

  return (
    <div className={styles.container}>
      {persistLogin(
        <>
          <Head>
            <title>Planner App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <div className={styles.block}>
            <h1>Welcome!</h1>
            <p>{time}</p>
          </div>
          <div>
            <Link href='/users'>
              <a>users</a>
            </Link>
          </div>
        </>
      )}
    </div>
  )
}
Home.getInitialProps = ({ req }) => {
  const cookies = parseCookies(req)
  return {
    initialPersistValue: cookies.persist,
  }
}
