import Head from 'next/head'
import { useState, useEffect } from 'react'
import styles from '../styles/Index.module.css'
import Link from 'next/link'

export default function Home() {
  const [time, setTime] = useState()
  const date = new Date()
  useEffect(() => {
    const timer = setInterval(
      () =>
        setTime(
          new Intl.DateTimeFormat('en-US', {
            dateStyle: 'full',
            timeStyle: 'long',
          }).format(date)
        ),
      1000
    )
    return () => {
      clearInterval(timer)
    }
  }, [time])

  return (
    <div className={styles.container}>
      <Head>
        <title>Planner App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Welcome!</h1>
      <p>{time}</p>
      <div className={styles.block}></div>
      <div>
        <Link href='/users'>
          <a>users</a>
        </Link>
      </div>
    </div>
  )
}
